language: php

php:
    - 5.6
    - 7.0
    - 7.1

install:
    - composer install

script: mkdir -p build/logs && vendor/bin/kahlan --reporter=tap:reports/results.tap --reporter=json:reports/results.json --reporter=verbose --coverage=4 --clover=build/logs/clover.xml

after_script:
    - php vendor/bin/coveralls -v
